In [1]:
import numpy as np

### creating numpy array

In [10]:
# converting python list
my_list = [1,2,3]
type(my_list)

list

In [11]:
my_arr = np.array(my_list)
my_arr

array([1, 2, 3])

In [12]:
print(my_arr, type(my_arr), sep=' ')

[1 2 3] <class 'numpy.ndarray'>


In [16]:
my_matrix = [[1,2,3], [4,5,6], [6,8,9]] # 3 by 3 matrix
my_matrix

[[1, 2, 3], [4, 5, 6], [6, 8, 9]]

In [17]:
my_numpy_matrix = np.array(my_matrix)
my_numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [6, 8, 9]])

In [21]:
# by directly assigning it using np.array
my_3dim_matrix = np.array([[[1,2,3],[4,5,6]], [[7,8,9], [10,11,12]]]) # 2 x 2 x 3 array
my_3dim_matrix

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### built in functions and methods:

In [24]:
np.arange(0, 10, 2) # equivalent of range()

array([0, 2, 4, 6, 8])

In [27]:
np.zeros([3, 2,2], dtype = int)

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [28]:
np.ones([1,2])

array([[1., 1.]])

In [37]:
np.linspace(0, 10, 3) # np.linspace(start, stop, n) -> returns n numbers evenly spaced between start and stop

array([ 0.,  5., 10.])

In [38]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
np.random.rand(2,3) # returns samples from uniform distribution

array([[0.49020087, 0.30938706, 0.34149832],
       [0.45577507, 0.72119927, 0.53470189]])

In [44]:
np.random.randn(2) # returns samples from the "standard normal" distribution (close to 0 are more likely to occur)

array([ 0.65846428, -0.27692606])

In [46]:
np.random.randn(2,2)

array([[ 0.86389888,  0.53948814],
       [-1.36347242,  0.42479983]])

In [50]:
np.random.randint(0, 101, (2,1))

array([[12],
       [15]])

In [59]:
np.random.seed(42) # for reproduciblity
np.random.randint(0, 10)

6

In [74]:
ranarr = np.random.randint(0,101,(2,10))
ranarr

array([[83, 91, 59, 70, 43,  7, 46, 34, 77, 80],
       [35, 49,  3,  1,  5, 53,  3, 53, 92, 62]])

In [75]:
ranarr.max()

92

In [76]:
ranarr.min()

1

In [77]:
ranarr.argmax()

18

In [78]:
ranarr.argmin()

13

In [80]:
ranarr.dtype

dtype('int32')

In [81]:
arr.shape

(25,)

In [82]:
arr.reshape(5,5).shape

(5, 5)